# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    admin.corpuscharacteristicvalue:
        class: AppBundle\Admin\CorpusCharacteristicValueAdmin
        arguments: [~, AppBundle\Entity\CorpusCharacteristicValue, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Corpus Characteristic Value }
            
    admin.corpuscharacteristic:
        class: AppBundle\Admin\CorpusCharacteristicAdmin
        arguments: [~, AppBundle\Entity\CorpusCharacteristic, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Corpus Characteristic  }
            
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
            
    your.log.handler:
        class: %monolog.handler.stream.class%
        arguments: [ %kernel.logs_dir%/%kernel.environment%.yourFileName.log ]
        
    your.logger:
        class: %monolog.logger.class%
        arguments: [ nameOfLoggingChannel ]
        calls: [ [pushHandler, [@your.log.handler]] ]
            